2024-06-20T04:17:01.775 INFO app=vAPI action=success signature="Starting vAPI on port 8081 using vAPI.yaml"
2024-06-20T04:17:01.775 INFO Starting vAPI on port 8081 using vAPI.yaml
2024-06-20T04:17:01.823 WARNING `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2024-06-20T04:17:01.847 INFO Adding spec json: /openapi.json
2024-06-20T04:17:01.847 WARNING The swagger_ui directory could not be found.
    Please install connexion with extra install: pip install connexion[swagger-ui]
    or provide the path to your local installation by passing swagger_path=<your path>

2024-06-20T04:17:04.146 ERROR AttributeError("'Request' object has no attribute 'environ'")
Traceback (most recent call last):
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/swagger_ui.py", line 222, in __call__
    await self.router(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 806, in app
    await self.default(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/swagger_ui.py", line 235, in default_fn
    await self.app(original_scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/routing.py", line 154, in __call__
    await self.router(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/routing.py", line 48, in __call__
    await self.next_app(original_scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/security.py", line 106, in __call__
    await self.next_app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/request_validation.py", line 142, in __call__
    await self.next_app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/lifespan.py", line 26, in __call__
    await self.next_app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/abstract.py", line 264, in __call__
    return await operation(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/middleware/context.py", line 25, in __call__
    await self.next_app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/apps/flask.py", line 151, in __call__
    return await self.asgi_app(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 165, in __call__
    return await responder(scope, receive, send)
  File "/home/uocx/.local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 200, in __call__
    await self.loop.run_in_executor(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/uocx/.local/lib/python3.10/site-packages/a2wsgi/wsgi.py", line 256, in wsgi
    iterable = self.app(environ, start_response)
  File "/home/uocx/.local/lib/python3.10/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/home/uocx/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/uocx/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/uocx/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/uocx/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/apps/flask.py", line 68, in __call__
    return self.fn(*args, **kwargs)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/decorators/main.py", line 134, in wrapper
    return decorated_function(request)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/decorators/response.py", line 171, in wrapper
    handler_response = function(*args, **kwargs)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/decorators/parameter.py", line 87, in wrapper
    return function(**kwargs)
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/decorators/main.py", line 123, in wrapper
    return function(*args, **kwargs)
  File "/home/uocx/Desktop/ALLFILES/WorkFolders/2024/June/vulnerablevagrant/code/api1/vAPI.py", line 34, in get_root
    src_ip = connexion.request.environ.get(
  File "/home/uocx/.local/lib/python3.10/site-packages/connexion/lifecycle.py", line 243, in __getattr__
    return getattr(self._starlette_request, item)
AttributeError: 'Request' object has no attribute 'environ'
2024-06-20T04:17:04.203 WARNING HTTPException(status_code=404, detail='The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.')
2024-06-20T04:17:04.203 ERROR HTTPException(status_code=404, detail='The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.')
2024-06-20T04:18:22.535 INFO app=vAPI action=success signature="Starting vAPI on port 8081 using vAPI.yaml"
2024-06-20T04:18:22.535 INFO Starting vAPI on port 8081 using vAPI.yaml
2024-06-20T04:18:22.582 WARNING `ConnexionMiddleware.run` is optimized for development. For production, run using a dedicated ASGI server.
2024-06-20T04:18:22.582 ERROR app=vAPI action=failure signature="Starting vAPI failed with exception: run() got an unexpected keyword argument 'debug'"
